# Generated by Django 4.0.4 on 2022-06-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0002_rename_disc_certs_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='certs',
            name='exam_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
