# Generated by Django 4.0.4 on 2022-06-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0003_certs_exam_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certs',
            options={'ordering': ['created_at'], 'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AlterField(
            model_name='certs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='certs',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='certs',
            name='doc_pdf',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='certs',
            name='exam_name',
            field=models.CharField(max_length=50, verbose_name='Наименование экзамена'),
        ),
        migrations.AlterField(
            model_name='certs',
            name='exam_type',
            field=models.CharField(max_length=10, verbose_name='Тип экзамена'),
        ),
        migrations.AlterField(
            model_name='certs',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='certs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
